name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Check Python version
        run: python --version
